before:
  hooks:
    - go mod tidy

builds:
  - id: "gidevice-cli"
    main: .
    binary: gidevice

    goos:
      - windows
      - freebsd
      - openbsd
      - linux
      - darwin

    goarm:
      - 7

    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64


archives:
  - id: "gidevice-cli"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
